<<<<<<< HEAD
# Generated by Django 3.2.25 on 2025-05-07 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikeinfo',
            name='user',
        ),
    ]
=======
# Generated by Django 3.2.25 on 2025-05-07 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikeinfo',
            name='user',
        ),
    ]
>>>>>>> e2bf320907d220dd96f146c20bc537caecd30fd4
