# Generated by Django 3.2.25 on 2025-05-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_remove_bikeinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('confirmed', 'Confirmed')], default='Pending', max_length=20),
        ),
    ]
