<<<<<<< HEAD
# Generated by Django 3.2.25 on 2025-05-07 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_rent_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='total_cost',
        ),
    ]
=======
# Generated by Django 3.2.25 on 2025-05-07 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_rent_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='total_cost',
        ),
    ]
>>>>>>> e2bf320907d220dd96f146c20bc537caecd30fd4
