# Generated by Django 3.2.25 on 2025-05-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_remove_rent_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10000),
        ),
    ]
